#!/bin/bash

# configure_docker.debian.sh - Debian-specific Docker Configuration
# Part of the OpenProject deployment framework

set -e  # Exit on any error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/../../interactive_config.cfg"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

echo "=========================================="
echo "Debian-specific Docker Configuration"
echo "=========================================="

# Function to load configuration
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
        echo "✓ Configuration loaded from $(basename "$CONFIG_FILE")"
    else
        echo "❌ Configuration file not found: $CONFIG_FILE"
        exit 1
    fi
}

# Function to update .env file with Debian-specific variables
update_env_file() {
    local env_file="$PROJECT_ROOT/.env"
    
    echo "Updating .env file with configuration and Debian-specific variables..."
    
    # Ensure .env file exists
    if [ ! -f "$env_file" ]; then
        echo "❌ .env file not found: $env_file"
        exit 1
    fi
    
    # Update .env file with values from interactive_config.cfg
    if [ -n "$OPENPROJECT_HOST_NAME" ]; then
        if grep -q "^OPENPROJECT_HOST__NAME=" "$env_file"; then
            sed -i "s/^OPENPROJECT_HOST__NAME=.*/OPENPROJECT_HOST__NAME=$OPENPROJECT_HOST_NAME/" "$env_file"
        else
            echo "OPENPROJECT_HOST__NAME=$OPENPROJECT_HOST_NAME" >> "$env_file"
        fi
        echo "✓ Updated hostname: $OPENPROJECT_HOST_NAME"
    fi
    
    if [ -n "$OPENPROJECT_HTTPS" ]; then
        if grep -q "^OPENPROJECT_HTTPS=" "$env_file"; then
            sed -i "s/^OPENPROJECT_HTTPS=.*/OPENPROJECT_HTTPS=$OPENPROJECT_HTTPS/" "$env_file"
        else
            echo "OPENPROJECT_HTTPS=$OPENPROJECT_HTTPS" >> "$env_file"
        fi
        echo "✓ Updated HTTPS setting: $OPENPROJECT_HTTPS"
    fi
    
    if [ -n "$OPENPROJECT_TAG" ]; then
        if grep -q "^TAG=" "$env_file"; then
            sed -i "s/^TAG=.*/TAG=$OPENPROJECT_TAG/" "$env_file"
        else
            echo "TAG=$OPENPROJECT_TAG" >> "$env_file"
        fi
        echo "✓ Updated OpenProject tag: $OPENPROJECT_TAG"
    fi
    
    if [ -n "$DEFAULT_DBADMIN_PASSWORD" ]; then
        if grep -q "^OPENPROJECT_ADMIN_PASSWORD=" "$env_file"; then
            sed -i "s/^OPENPROJECT_ADMIN_PASSWORD=.*/OPENPROJECT_ADMIN_PASSWORD=$DEFAULT_DBADMIN_PASSWORD/" "$env_file"
        else
            echo "OPENPROJECT_ADMIN_PASSWORD=$DEFAULT_DBADMIN_PASSWORD" >> "$env_file"
        fi
        echo "✓ Updated admin password"
    fi
    
    # Add Debian-specific environment variables
    {
        echo ""
        echo "# Debian-specific Docker configuration"
        echo "DOCKER_BUILDKIT=1"
        echo "COMPOSE_DOCKER_CLI_BUILD=1"
        echo "DEBIAN_FRONTEND=noninteractive"
        echo "DEBIAN_PRIORITY=critical"
        echo "APT_LISTCHANGES_FRONTEND=none"
    } >> "$env_file"
    
    echo "✓ .env file updated with configuration and Debian-specific variables"
}

# Function to create docker-compose.override.yml with Debian optimizations
create_override_file() {
    local override_file="$PROJECT_ROOT/docker-compose.override.yml"
    
    echo "Creating docker-compose.override.yml with Debian optimizations..."
    
    cat > "$override_file" << 'EOF'
# docker-compose.override.yml - Debian-specific OpenProject optimizations
# Generated by configure_docker.debian.sh

version: '3.8'

services:
  db:
    environment:
      # Debian-specific PostgreSQL optimizations
      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8 --encoding=UTF8"
    volumes:
      # APT cache volume for faster builds
      - apt-cache:/var/cache/apt
    sysctls:
      # Debian kernel optimizations for PostgreSQL
      vm.overcommit_memory: 2
      vm.overcommit_ratio: 80

  web:
    environment:
      # Debian-specific Rails optimizations
      DEBIAN_FRONTEND: noninteractive
      APT_LISTCHANGES_FRONTEND: none
      RAILS_ENV: "${RAILS_ENV:-production}"
    volumes:
      # APT cache volume for faster builds  
      - apt-cache:/var/cache/apt
      # Debian-specific temp directory
      - /tmp:/tmp:rw
    sysctls:
      # Debian kernel optimizations for Rails
      net.core.somaxconn: 65535
      net.ipv4.tcp_tw_reuse: 1

  proxy:
    environment:
      # Debian-specific Caddy optimizations
      DEBIAN_FRONTEND: noninteractive
    ports:
      # Standard HTTP/HTTPS ports for Debian UFW rules
      - "80:80"
      - "443:443"
    volumes:
      # APT cache volume for faster builds
      - apt-cache:/var/cache/apt

volumes:
  # Debian APT cache volume for faster package installations
  apt-cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=512m,uid=0,gid=0"

networks:
  default:
    driver: bridge
    driver_opts:
      # Debian-specific bridge optimizations
      com.docker.network.bridge.name: "openproject-br"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
EOF

    echo "✓ docker-compose.override.yml created with Debian optimizations"
}

# Function to configure UFW firewall rules
configure_ufw_firewall() {
    echo "Configuring UFW firewall for OpenProject..."
    
    # Check if UFW is installed and active
    if command -v ufw >/dev/null 2>&1; then
        echo "✓ UFW firewall detected"
        
        # Allow OpenProject ports
        echo "Configuring UFW rules for OpenProject..."
        sudo ufw allow 80/tcp comment 'OpenProject HTTP'
        sudo ufw allow 443/tcp comment 'OpenProject HTTPS'
        
        # Allow SSH if not already allowed
        sudo ufw allow ssh comment 'SSH access'
        
        echo "✓ UFW firewall configured for OpenProject"
    else
        echo "⚠ UFW not installed, skipping firewall configuration"
    fi
}

# Function to optimize systemd for Docker
configure_systemd_docker() {
    echo "Configuring systemd optimizations for Docker..."
    
    local systemd_override_dir="/etc/systemd/system/docker.service.d"
    local systemd_override_file="$systemd_override_dir/debian-override.conf"
    
    # Create systemd override directory
    if [ ! -d "$systemd_override_dir" ]; then
        sudo mkdir -p "$systemd_override_dir"
    fi
    
    # Create Debian-specific systemd override
    sudo tee "$systemd_override_file" > /dev/null << 'EOF'
[Service]
# Debian-specific Docker service optimizations
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TasksMax=1048576
OOMScoreAdjust=-999

# Debian-specific environment
Environment="DEBIAN_FRONTEND=noninteractive"
Environment="APT_LISTCHANGES_FRONTEND=none"

# Restart policy for Debian systems
Restart=always
RestartSec=10s
EOF

    # Reload systemd and restart Docker
    sudo systemctl daemon-reload
    sudo systemctl restart docker
    
    echo "✓ Systemd Docker service optimized for Debian"
}

# Function to configure APT for Docker builds
configure_apt_optimizations() {
    echo "Configuring APT optimizations for Docker builds..."
    
    # Create APT configuration for Docker builds
    local apt_config_dir="/etc/apt/apt.conf.d"
    local apt_docker_conf="$apt_config_dir/99-docker-debian"
    
    sudo tee "$apt_docker_conf" > /dev/null << 'EOF'
// Debian-specific APT optimizations for Docker builds
APT::Install-Recommends "false";
APT::Install-Suggests "false";
APT::Get::Assume-Yes "true";
APT::Get::Fix-Missing "true";
Dpkg::Use-Pty "0";
APT::Acquire::Retries "3";
EOF

    echo "✓ APT optimized for Docker builds"
}

# Function to show Debian configuration summary
show_debian_summary() {
    echo
    echo "Debian Docker Configuration Summary:"
    echo "==================================="
    echo "✓ .env file updated with Debian-specific variables"
    echo "✓ docker-compose.override.yml created with Debian optimizations"
    echo "✓ UFW firewall configured (if available)"
    echo "✓ Systemd Docker service optimized"
    echo "✓ APT configured for efficient Docker builds"
    echo
    echo "Debian-specific optimizations include:"
    echo "  - BuildKit support enabled"
    echo "  - APT cache volumes for faster builds"
    echo "  - UFW firewall rules for ports 80/443"
    echo "  - Systemd service limits and restart policies"
    echo "  - PostgreSQL and Rails environment optimizations"
    echo
}

# Main execution
main() {
    echo "Starting Debian-specific Docker configuration..."
    echo
    
    # Load configuration
    load_config
    echo
    
    # Update .env file with Debian-specific variables
    update_env_file
    echo
    
    # Create docker-compose.override.yml with Debian optimizations
    create_override_file
    echo
    
    # Configure UFW firewall
    configure_ufw_firewall
    echo
    
    # Configure systemd optimizations
    configure_systemd_docker
    echo
    
    # Configure APT optimizations
    configure_apt_optimizations
    echo
    
    # Show summary
    show_debian_summary
    
    echo "🎉 Debian-specific Docker configuration completed successfully!"
}

# Run main function
main "$@"