#!/usr/bin/env bash
# Shared helper to detect deployment values and render deployment artifacts
# Intended to be sourced by small CLI wrappers or configure scripts.

# detect_deployment_values PROJECT_ROOT DEFAULTS_FILE CONFIG_FILE
detect_deployment_values() {
    local project_root=${1:-}
    local defaults_file=${2:-}
    local config_file=${3:-}

    # Resolve sensible defaults if not provided
    if [ -z "$project_root" ]; then
        # walk up from this file's dir until docker-compose.yml is found
        local cur
        cur="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        while [ "$cur" != "/" ]; do
            if [ -f "$cur/docker-compose.yml" ]; then
                project_root="$cur"
                break
            fi
            cur="$(dirname "$cur")"
        done
        if [ -z "$project_root" ]; then
            project_root="/opt/openproject"
        fi
    fi

    PROJECT_ROOT="$project_root"

    # defaults/config paths fall back to conventional locations under scripts/
    DEFAULTS_FILE=${defaults_file:-"$PROJECT_ROOT/scripts/installation_scripts/interactive_config.cfg.defaults"}
    CONFIG_FILE=${config_file:-"$PROJECT_ROOT/scripts/installation_scripts/interactive_config.cfg"}

    # Load defaults (not exported globally by default files, but we will source)
    if [ -f "$DEFAULTS_FILE" ]; then
        # shellcheck source=/dev/null
        source "$DEFAULTS_FILE"
    fi

    # Load interactive config if present
    if [ -f "$CONFIG_FILE" ]; then
        # shellcheck source=/dev/null
        source "$CONFIG_FILE"
    fi

    # Compute values with same fallback behavior as previous generator
    APP_HOST=${APP_HOST:-web}
    DOMAIN_NAME=${DOMAIN_NAME:-${OPENPROJECT_HOST_NAME:-}}
    # Canonical: use a path-only runtime value RAILS_RELATIVE_URL_ROOT.
    # Accept RAILS_RELATIVE_URL_ROOT if already present; otherwise compute
    # it from the namespace settings.
    URI_NAMESPACE=${URI_NAMESPACE:-StatesmenProjects}
    RAILS_RELATIVE_URL_ROOT=${RAILS_RELATIVE_URL_ROOT:-}
    URI_NAMESPACE_ENABLED=${URI_NAMESPACE_ENABLED:-false}
    PROXY_TLS_MODE=${PROXY_TLS_MODE:-internal}
    PROXY_HTTP_PORT=${PROXY_HTTP_PORT:-80}
    PROXY_HTTPS_PORT=${PROXY_HTTPS_PORT:-443}
    PROXY_HTTPS_REDIRECT=${PROXY_HTTPS_REDIRECT:-}

    # Compute the path-only runtime value used by Caddy and the application.
    # Priority: explicit RAILS_RELATIVE_URL_ROOT > computed from URI_NAMESPACE when enabled > '/'
    if [ -z "${RAILS_RELATIVE_URL_ROOT}" ]; then
        if [[ "${URI_NAMESPACE_ENABLED,,}" = "true" ]] && [ -n "${URI_NAMESPACE}" ]; then
            ns="${URI_NAMESPACE#/}"
            ns="${ns%/}"
            RAILS_RELATIVE_URL_ROOT="/${ns}"
        else
            RAILS_RELATIVE_URL_ROOT="/"
        fi
    fi

    # Destination paths
    ENV_PATH="$PROJECT_ROOT/.env"
    OVERRIDE_PATH="$PROJECT_ROOT/docker-compose.override.yml"
    CADDY_TEMPLATE_PATH="$PROJECT_ROOT/proxy/Caddyfile.template"
}

render_env() {
    cat <<EOF
# Generated by config_render.sh
RAILS_RELATIVE_URL_ROOT="${RAILS_RELATIVE_URL_ROOT}"
OPENPROJECT_HOST_NAME="${DOMAIN_NAME}"
URI_NAMESPACE="${URI_NAMESPACE}"
URI_NAMESPACE_ENABLED="${URI_NAMESPACE_ENABLED}"
PROXY_TLS_MODE="${PROXY_TLS_MODE}"
PROXY_HTTP_PORT="${PROXY_HTTP_PORT}"
PROXY_HTTPS_PORT="${PROXY_HTTPS_PORT}"
PROXY_HTTPS_REDIRECT="${PROXY_HTTPS_REDIRECT}"
EOF
}

render_override() {
        cat <<EOF
services:
    web:
        environment:
            # Backwards-compat mapping to keep older consumers happy
            OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${RAILS_RELATIVE_URL_ROOT:-}"
EOF
}

render_caddy_template() {
    SITE_HDR_HTTP=":${PROXY_HTTP_PORT}"
    if [ -n "${DOMAIN_NAME}" ]; then
        SITE_HDR_HTTPS=":${PROXY_HTTPS_PORT} ${DOMAIN_NAME}"
    else
        SITE_HDR_HTTPS=":${PROXY_HTTPS_PORT}"
    fi

    cat <<EOF
{
    auto_https disable_redirects
}
${SITE_HDR_HTTP} {
    # Redirect all HTTP to HTTPS
    redir https://{host}{uri} 308
}

${SITE_HDR_HTTPS} {
EOF

    if [ -z "$RAILS_RELATIVE_URL_ROOT" ] || [ "$RAILS_RELATIVE_URL_ROOT" = "/" ]; then
        cat <<'EOF'
    tls {
        ca https://acme-staging-v02.api.letsencrypt.org/directory
    }

    reverse_proxy * ${APP_HOST}:8080 {
        header_up X-Forwarded-Proto {http.request.scheme}
        header_up X-Forwarded-For {remote}
        header_up Host {http.request.host}
    }

    file_server
    log
}
EOF
    else
        cat <<EOF
    tls {
        ca https://acme-staging-v02.api.letsencrypt.org/directory
    }

        @app_prefix {
            path ${RAILS_RELATIVE_URL_ROOT}*
    }

    reverse_proxy @app_prefix ${APP_HOST}:8080 {
        header_up X-Forwarded-Proto {http.request.scheme}
        header_up X-Forwarded-For {remote}
        header_up Host {http.request.host}
    }

    file_server
    log
}
EOF
    fi
}

backup_file() {
    local p=$1
    if [ -f "$p" ]; then
        local ts
        ts=$(date -u +%Y%m%dT%H%M%SZ)
        cp -a "$p" "${p}.bak.${ts}"
        echo "Backed up $p -> ${p}.bak.${ts}"
    fi
}

# write_files APPLY_FLAG SKIP_CADDY
write_files() {
    local apply=${1:-false}
    local skip_caddy=${2:-false}

    if [ "$apply" != "true" ]; then
        echo "DRY RUN: not writing files. Call write_files true to apply."
        return 0
    fi

    # .env
    backup_file "$ENV_PATH"
    render_env > "$ENV_PATH"
    echo "Wrote $ENV_PATH"

    # override
    backup_file "$OVERRIDE_PATH"
    render_override > "$OVERRIDE_PATH"
    echo "Wrote $OVERRIDE_PATH"

    # caddy template (optional)
    if [ "$skip_caddy" != "true" ]; then
        backup_file "$CADDY_TEMPLATE_PATH"
        render_caddy_template > "$CADDY_TEMPLATE_PATH"
        echo "Wrote $CADDY_TEMPLATE_PATH"
    else
        echo "Skipping Caddy template write (skip_caddy=true)"
    fi
}

print_summary() {
    cat <<EOF
Detected values:
    DOMAIN_NAME: ${DOMAIN_NAME}
    RAILS_RELATIVE_URL_ROOT (path used by app/proxy): ${RAILS_RELATIVE_URL_ROOT}
    URI_NAMESPACE: ${URI_NAMESPACE}
    URI_NAMESPACE_ENABLED: ${URI_NAMESPACE_ENABLED}
  PROXY_TLS_MODE: ${PROXY_TLS_MODE}

Files that will be generated:
  - ${ENV_PATH}
  - ${OVERRIDE_PATH}
  - ${CADDY_TEMPLATE_PATH}

Use write_files true to apply changes (this will back up existing files).
EOF
}

# validate_caddy: render the Caddy template to a temp file and validate
# using the official caddy Docker image. Returns caddy's exit code.
validate_caddy() {
    if ! command -v docker >/dev/null 2>&1; then
        echo "⚠ docker is not available on PATH; cannot run Caddy validation locally."
        return 2
    fi

    local tmpdir
    tmpdir=$(mktemp -d)
    local tmpfile="$tmpdir/Caddyfile.template"

    # Render into temporary file
    render_caddy_template > "$tmpfile"

    echo "Validating generated Caddyfile at $tmpfile using caddy Docker image..."

    # Run caddy validate inside the official image, mounting the tmpdir
    docker run --rm -v "$tmpdir":/work -w /work caddy:2 caddy validate --config /work/Caddyfile.template >"$tmpdir/validate.out" 2>&1
    local rc=$?

    if [ $rc -eq 0 ]; then
        echo "✓ Caddyfile validated successfully"
        cat "$tmpdir/validate.out"
    else
        echo "✗ Caddy validation failed (exit $rc). Output:" >&2
        sed -n '1,200p' "$tmpdir/validate.out" >&2 || true
    fi

    rm -rf "$tmpdir"
    return $rc
}

# validate_compose: render override to a temp file and run `docker compose config`
# Returns docker-compose exit code (0 = valid). If docker compose is missing,
# returns code 2 and prints a warning.
validate_compose() {
    if ! command -v docker >/dev/null 2>&1; then
        echo "⚠ docker is not available on PATH; cannot run docker compose validation."
        return 2
    fi

    if ! docker compose version >/dev/null 2>&1; then
        echo "⚠ docker compose is not available (or older docker CLI). Skipping compose validation."
        return 2
    fi

    local tmpdir
    tmpdir=$(mktemp -d)
    local tmpfile="$tmpdir/docker-compose.override.yml"

    render_override > "$tmpfile"

    echo "Validating docker-compose with base docker-compose.yml and generated override..."

    # Run docker compose config to validate merged compose (mounted by path)
    # Use PROJECT_ROOT if set, otherwise assume current directory
    local base_dir
    base_dir=${PROJECT_ROOT:-.}

    # docker compose expects to run in the directory containing the main compose file
    (cd "$base_dir" && docker compose -f docker-compose.yml -f "$tmpfile" config) >"$tmpdir/compose.out" 2>&1
    local rc=$?

    if [ $rc -eq 0 ]; then
        echo "✓ docker-compose validated successfully"
        sed -n '1,200p' "$tmpdir/compose.out" || true
    else
        echo "✗ docker-compose validation failed (exit $rc). Output:" >&2
        sed -n '1,200p' "$tmpdir/compose.out" >&2 || true
    fi

    rm -rf "$tmpdir"
    return $rc
}
